<?php

namespace Database\Seeders;

use App\Models\Crop;
use Illuminate\Database\Seeder;

class CropSeeder extends Seeder
{
    public function run(): void
    {
        $crops = [
            [
                'name' => 'Wheat',
                'scientific_name' => 'Triticum aestivum',
                'type' => 'Cereal',
                'season' => 'Rabi',
                'optimal_ph_min' => 6.0,
                'optimal_ph_max' => 7.0,
                'water_requirement_days' => 120,
            ],
            [
                'name' => 'Rice (Paddy)',
                'scientific_name' => 'Oryza sativa',
                'type' => 'Cereal',
                'season' => 'Kharif',
                'optimal_ph_min' => 5.5,
                'optimal_ph_max' => 6.5,
                'water_requirement_days' => 150,
            ],
            [
                'name' => 'Maize',
                'scientific_name' => 'Zea mays',
                'type' => 'Cereal',
                'season' => 'Kharif',
                'optimal_ph_min' => 5.8,
                'optimal_ph_max' => 7.0,
                'water_requirement_days' => 90,
            ],
            [
                'name' => 'Cotton',
                'scientific_name' => 'Gossypium',
                'type' => 'Fiber',
                'season' => 'Kharif',
                'optimal_ph_min' => 5.8,
                'optimal_ph_max' => 8.0,
                'water_requirement_days' => 180,
            ],
            [
                'name' => 'Sugarcane',
                'scientific_name' => 'Saccharum officinarum',
                'type' => 'Cash Crop',
                'season' => 'Year-round',
                'optimal_ph_min' => 6.5,
                'optimal_ph_max' => 7.5,
                'water_requirement_days' => 360,
            ],
            [
                'name' => 'Soybean',
                'scientific_name' => 'Glycine max',
                'type' => 'Oilseed',
                'season' => 'Kharif',
                'optimal_ph_min' => 6.0,
                'optimal_ph_max' => 7.5,
                'water_requirement_days' => 100,
            ],
            [
                'name' => 'Groundnut',
                'scientific_name' => 'Arachis hypogaea',
                'type' => 'Oilseed',
                'season' => 'Kharif',
                'optimal_ph_min' => 5.5,
                'optimal_ph_max' => 6.5,
                'water_requirement_days' => 80,
            ],
            [
                'name' => 'Mustard',
                'scientific_name' => 'Brassica juncea',
                'type' => 'Oilseed',
                'season' => 'Rabi',
                'optimal_ph_min' => 6.0,
                'optimal_ph_max' => 7.0,
                'water_requirement_days' => 120,
            ],
            [
                'name' => 'Potato',
                'scientific_name' => 'Solanum tuberosum',
                'type' => 'Vegetable',
                'season' => 'Rabi',
                'optimal_ph_min' => 5.0,
                'optimal_ph_max' => 6.0,
                'water_requirement_days' => 90,
            ],
            [
                'name' => 'Onion',
                'scientific_name' => 'Allium cepa',
                'type' => 'Vegetable',
                'season' => 'Rabi',
                'optimal_ph_min' => 6.0,
                'optimal_ph_max' => 7.0,
                'water_requirement_days' => 120,
            ],
            [
                'name' => 'Mango',
                'scientific_name' => 'Mangifera indica',
                'type' => 'Fruit',
                'season' => 'Summer',
                'optimal_ph_min' => 5.5,
                'optimal_ph_max' => 7.5,
                'water_requirement_days' => 180,
            ],
            [
                'name' => 'Banana',
                'scientific_name' => 'Musa spp.',
                'type' => 'Fruit',
                'season' => 'Year-round',
                'optimal_ph_min' => 5.5,
                'optimal_ph_max' => 7.0,
                'water_requirement_days' => 270,
            ],
            [
                'name' => 'Chickpea',
                'scientific_name' => 'Cicer arietinum',
                'type' => 'Pulse',
                'season' => 'Rabi',
                'optimal_ph_min' => 6.0,
                'optimal_ph_max' => 7.5,
                'water_requirement_days' => 100,
            ],
            [
                'name' => 'Turmeric',
                'scientific_name' => 'Curcuma longa',
                'type' => 'Spice',
                'season' => 'Kharif',
                'optimal_ph_min' => 5.8,
                'optimal_ph_max' => 6.5,
                'water_requirement_days' => 180,
            ],
            [
                'name' => 'Tea',
                'scientific_name' => 'Camellia sinensis',
                'type' => 'Cash Crop',
                'season' => 'Monsoon',
                'optimal_ph_min' => 4.5,
                'optimal_ph_max' => 5.5,
                'water_requirement_days' => 180,
            ],
            [
                'name' => 'Sesame',
                'scientific_name' => 'Sesamum indicum',
                'type' => 'Oilseed',
                'season' => 'Kharif',
                'optimal_ph_min' => 5.5,
                'optimal_ph_max' => 7.0,
                'water_requirement_days' => 100,
            ],
            [
                'name' => 'Grapes',
                'scientific_name' => 'Vitis vinifera',
                'type' => 'Fruit',
                'season' => 'Rabi',
                'optimal_ph_min' => 6.5,
                'optimal_ph_max' => 8.5,
                'water_requirement_days' => 150,
            ],
            [
                'name' => 'Coconut',
                'scientific_name' => 'Cocos nucifera',
                'type' => 'Cash Crop',
                'season' => 'Year-round',
                'optimal_ph_min' => 5.5,
                'optimal_ph_max' => 7.0,
                'water_requirement_days' => 200,
            ],
            [
                'name' => 'Pepper',
                'scientific_name' => 'Piper nigrum',
                'type' => 'Spice',
                'season' => 'Monsoon',
                'optimal_ph_min' => 5.5,
                'optimal_ph_max' => 6.5,
                'water_requirement_days' => 220,
            ],
            [
                'name' => 'Ginger',
                'scientific_name' => 'Zingiber officinale',
                'type' => 'Spice',
                'season' => 'Monsoon',
                'optimal_ph_min' => 5.6,
                'optimal_ph_max' => 6.5,
                'water_requirement_days' => 210,
            ],
            [
                'name' => 'Apple',
                'scientific_name' => 'Malus domestica',
                'type' => 'Fruit',
                'season' => 'Rabi',
                'optimal_ph_min' => 6.0,
                'optimal_ph_max' => 7.0,
                'water_requirement_days' => 180,
            ],
            [
                'name' => 'Cashew',
                'scientific_name' => 'Anacardium occidentale',
                'type' => 'Nut',
                'season' => 'Kharif',
                'optimal_ph_min' => 5.0,
                'optimal_ph_max' => 6.5,
                'water_requirement_days' => 240,
            ],
            [
                'name' => 'Arecanut',
                'scientific_name' => 'Areca catechu',
                'type' => 'Nut',
                'season' => 'Monsoon',
                'optimal_ph_min' => 5.0,
                'optimal_ph_max' => 6.5,
                'water_requirement_days' => 280,
            ],
            [
                'name' => 'Millet',
                'scientific_name' => 'Panicum miliaceum',
                'type' => 'Cereal',
                'season' => 'Kharif',
                'optimal_ph_min' => 5.5,
                'optimal_ph_max' => 7.0,
                'water_requirement_days' => 70,
            ],
        ];

        foreach ($crops as $crop) {
            Crop::updateOrCreate(['name' => $crop['name']], $crop);
        }
    }
}
